
effect Fail(): Int

def main() = {
  try {
    println(0);
    do Fail();
    println(2);
    3
  } with Fail { () =>
    1
  }
}

