def foo() =
  def bar() = 42 // ERROR enclosed in braces